//import type { NextPage } from 'next';
import Head from 'next/head';
import Image from "next/image";
import { Footer } from '../src/components/Footer';
import { Heading } from '../src/components/Heading';


import styles from '../styles/Home.module.css';

const Home = () => {

  return (
    <>
      <Heading />
      <div className={styles.container}>
        <Head>
          <title>Mindset! | Maior E-commerce</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>

        </main>
      </div>
      <Footer />
    </>
  )
}

export default Home
